[package]
name = "mail-api"
version = "0.1.0"
edition = "2021"

[dependencies]
graph-rs-sdk = "2.0.1"
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
warp = "0.3"