[package]
name = "Example-API"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
warp = "0.3"
pretty_env_logger = "0.4"
log = "0.4"